"""Adicionar Tabela Tarefa

Revision ID: 47784dc9585a
Revises: a077063db3fb
Create Date: 2024-10-10 17:03:20.420707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47784dc9585a'
down_revision: Union[str, None] = 'a077063db3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tarefa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('data_de_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_de_fim', sa.DateTime(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'ATRASADO', name='status'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tarefa_id'), 'Tarefa', ['id'], unique=False)
    op.create_index(op.f('ix_Tarefa_id_usuario'), 'Tarefa', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_Tarefa_titulo'), 'Tarefa', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tarefa_titulo'), table_name='Tarefa')
    op.drop_index(op.f('ix_Tarefa_id_usuario'), table_name='Tarefa')
    op.drop_index(op.f('ix_Tarefa_id'), table_name='Tarefa')
    op.drop_table('Tarefa')
    # ### end Alembic commands ###
