"""add_tabela_carteira_e_transferencia

Revision ID: 54036014b612
Revises: a077063db3fb
Create Date: 2025-01-25 22:04:38.411481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54036014b612"
down_revision: Union[str, None] = "a077063db3fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Carteira",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("id_usuario", sa.Uuid(), nullable=False),
        sa.Column("saldo_em_centavos", sa.Integer(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_usuario"],
            ["Usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Carteira_id"), "Carteira", ["id"], unique=False)
    op.create_table(
        "Transferencia",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("id_usuario_origem", sa.Uuid(), nullable=False),
        sa.Column("id_carteira_origem", sa.Uuid(), nullable=False),
        sa.Column("id_usuario_destino", sa.Uuid(), nullable=False),
        sa.Column("id_carteira_destino", sa.Uuid(), nullable=False),
        sa.Column("valor_transferido_em_centavos", sa.Integer(), nullable=False),
        sa.Column(
            "status_da_transferencia",
            sa.Enum(
                "PENDENTE",
                "PROCESSANDO",
                "CONCLUIDO",
                "CANCELADO",
                name="statusdetransferencia",
            ),
            nullable=False,
        ),
        sa.Column("transferido_em", sa.DateTime(), nullable=False),
        sa.Column("completado_em", sa.DateTime(), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_carteira_destino"],
            ["Carteira.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_carteira_origem"],
            ["Carteira.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario_destino"],
            ["Usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario_origem"],
            ["Usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Transferencia_id"), "Transferencia", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Transferencia_id"), table_name="Transferencia")
    op.drop_table("Transferencia")
    op.drop_index(op.f("ix_Carteira_id"), table_name="Carteira")
    op.drop_table("Carteira")
    # ### end Alembic commands ###
